export default function Features() {
    const features = [
      {
        icon: "🤖",
        title: "AI-Powered Curriculum",
        description: "Personalized learning paths generated by advanced AI based on your goals, pace, and learning style."
      },
      {
        icon: "💬",
        title: "Interactive Mentorship",
        description: "Chat with your AI mentor 24/7. Ask questions, get instant feedback, and never feel stuck again."
      },
      {
        icon: "📊",
        title: "Track Your Progress",
        description: "Visual dashboards show your learning journey. See what you've mastered and what's next."
      },
      {
        icon: "🎯",
        title: "Real-World Projects",
        description: "Learn by building actual projects, not just theory. Get hands-on experience from day one."
      },
      {
        icon: "⚡",
        title: "Learn Faster",
        description: "AI adapts to your speed. Fast learners move quickly, beginners get extra support automatically."
      },
      {
        icon: "🏆",
        title: "Skill Certificates",
        description: "Earn certificates upon completion. Share your achievements on LinkedIn and boost your career."
      }
    ];
  
    return (
      <section id="features" className="py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          
          {/* Section Header */}
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
              Why Choose <span className="bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">LearnWithAI</span>?
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Traditional courses are outdated. We use cutting-edge AI to give you a personalized, adaptive learning experience.
            </p>
          </div>
  
          {/* Features Grid */}
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <div 
                key={index}
                className="group p-8 rounded-2xl border-2 border-gray-100 hover:border-purple-200 hover:shadow-xl transition-all duration-300 cursor-pointer"
              >
                {/* Icon */}
                <div className="w-16 h-16 bg-gradient-to-br from-purple-100 to-pink-100 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                  <span className="text-4xl">{feature.icon}</span>
                </div>
  
                {/* Title */}
                <h3 className="text-2xl font-bold text-gray-900 mb-3">
                  {feature.title}
                </h3>
  
                {/* Description */}
                <p className="text-gray-600 leading-relaxed">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
  
          {/* Bottom CTA */}
          <div className="text-center mt-16">
            <button className="bg-gradient-to-r from-purple-600 to-pink-600 text-white px-8 py-4 rounded-full text-lg font-semibold hover:opacity-90 transition shadow-lg">
              Explore All Features →
            </button>
          </div>
  
        </div>
      </section>
    );
  }